server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true

      routes:
        - id: firstms
          uri: lb://FIRSTMS
          predicates:
            - Path= /dummy-firstms/**
          filters:
            - RewritePath= /dummy-firstms/(?<path>.*), /$\{path}
        - id: ms-client
          uri: lb://MS-CLIENT
          predicates:
            - Path= /dummy/**
          filters:
            - RewritePath= /dummy/(?<path>.*), /$\{path}